language: java
jdk:
  - openjdk8

branches:
    only:
      - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - kahlman@naver.com


before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동 후 전체 압축
  - cd ../ & mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/asyu-boot-webservice.zip

deploy:
  - provider: s3
    access_key_id: AKIAWFTGBQ5JPSXPJQTE
    secret_access_key: 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
    bucket: asyu-webservice-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip파일 접근을 private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: AKIAWFTGBQ5JPSXPJQTE
    secret_access_key: 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
    bucket: asyu-webservice-build
    key: asyu-boot-webservice.zip
    bundle_type: zip
    application: asyu-boot-webservice
    deploy_group: asyu-boot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
